channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
 - pandas=2.1.1
 - plotly=5.17.0
 - plotly-orca=1.3.1
 - seaborn=0.13.0
 - numpy=1.26.0
 - matplotlib>=3.8.0
 - python-kaleido=0.2.1
 - salmon=1.10.2
 - star=2.7.11a
 - samtools=1.19.2